# Generated by Django 5.0.6 on 2024-05-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taskiid', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=55, null=True)),
                ('teacher', models.CharField(max_length=55, null=True)),
                ('choose', models.CharField(choices=[('Low', 'Low'), ('High', 'High'), ('Medium', 'Medium')], max_length=6, null=True)),
                ('Description', models.TextField(blank=True, max_length=160, null=True)),
                ('admin', models.CharField(max_length=15, null=True)),
                ('completed', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
