# Generated by Django 5.0.6 on 2024-05-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edit', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='Taskiid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
